name: Retry Step
description: 'Retry a step on failure or timeout'
inputs:
  max_attempts:
    description: Number of attempts to make before failing the step
    required: true
    default: 2
  command:
    description: The command to run
    required: true
  flaky_test_output_lines:
    description: Specify which lines in output indicate that the failure is flaky. Note - if not specified, all failures are considered as real failures.
    required: false
runs:
  using: 'node20'
  main: 'dist/index.js'
